package com.example.frontdoor.backend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import jakarta.validation.constraints.NotBlank;

import javax.validation.constraints.*;


@Document(collection="Docs")
public class docsModel {
    // is autogenerated by mongodb document 
    @Id
    private String id;
    // 
    @NotBlank
    private String name;

    @NotBlank
    private String location;

    @NotBlank
    private String speciality;

    @Min(1)
    @Max(5)
    private Integer rating;

    public docsModel(){
        // empty because thats how it is on the tutorial
    }

    public docsModel(String name, String location, String speciality, Integer rating){
        this.name = name;
        this.location = location;
        this.speciality = speciality;
        this.rating = rating;
    }

    public String getId() {
        return id;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getLocation() {
        return location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    public String getSpeciality() {
        return speciality;
    }
    
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    public Integer getRating() {
        return rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Override
    public String toString() {
    return "Doctor [id=" + id + ", name=" + name + ", location=" + location + ", speciality=" + speciality + ", rating=" + rating + "]";
}
}
